### ISSUE TITLE
Psychic skills not adding to character sheet

### ISSUE THREAD

**Issue by aquafraternal** [Spice-King/foundry-swnr#18]
When you click the "No skills? Clear here to add some!" button in the skills tab and select "Add Psychic Skills", the psychic skills are not being added to the list of skills.  The same problem seems to apply for the Space Magic skills.

**Comment by Spice-King** [comment]
Fixed by 12b48d0349867a3be8a142bf920efd83d3c0ea07.

**Comment by desj16** [comment]
I just created a fresh world on version 0.3.5 and tried creating a new Psychic character. The "Add Psychic Skills" option is still not doing anything when attempting to add skills.
