### ISSUE TITLE
Armor Equip and Weapon Magazine Checkbox weird behaviour/not working.

### ISSUE THREAD

**Issue by Leolele99** [Spice-King/foundry-swnr#25]
Armor Equip Checkbox:
The checkbox to set any armor as equipped to increase a characters AC, often immediately deactivates itself again after being activated. Sometimes this resets the AC back to its basestat, sometimes the armor included AC is kept, even if the box is unchecked. Closing the character sheet and opening it again also regularily either unchecks the box, or resets the AC to basestat.

Weapon Magazine Checkbox:
The Magazine [Currrent] [Max] Checkbox in any of the ranged weapons doesn't seem to work. By default it is deactivated, but ammo is still subsctracted if the auto roll button of the weapon is used. Checking the checkbox to positive, doesnt change that behaviour.

**Comment by Spice-King** [comment]
First one was probably fixed in f22327fdf69ac314991cacc1cc85da2b5199d28f
Second one due to less than ideal formatting made it look like it was for the magazine count, but was just a marker for if a weapon was capable of suppressive fire. Should have been solved more or less in f0072777ccf0bce870c98ce165d6a3a87130ab47, would have been committed sooner but I spent two weeks playing around with it being unhappy with the results I was getting.

**Comment by Leolele99** [comment]
I am happy about the second one being included in a future fix.

I went back rn and checked my installed version and it is  0.3.5 and the first bug still persists even after a restart and can be reproduced easily for me. If you want I can upload a video.

**Comment by Spice-King** [comment]
Yea, all that code is not in a released version yet. I've been poking about to make sure it all works and I've broken nothing in the update before I push 0.4.0 out.

**Comment by Leolele99** [comment]
Oh sorry then, I was confused by the delivery method of foundry addons. 
Looking forward to the next update.

**Comment by Janooba** [comment]
Just picked up the latest 0.4.0b release and it seems the `Armor Equip Checkbox` issue is still there. It appears the issue only manifests from the clients end, if that helps any.
